version: "3"
services:
  server:
    image: redash/redash:latest
    container_name: redash_server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    env_file: redash.env
    command: server
  scheduler:
    image: redash/redash:latest
    container_name: redash_scheduler
    restart: always
    depends_on:
      - server
    env_file: redash.env
    command: scheduler
  worker:
    image: redash/redash:latest
    container_name: redash_worker
    restart: always
    depends_on:
      - server
    env_file: redash.env
    command: worker
  postgres:
    image: postgres:latest
    env_file: redash.env
  redis:
    image: redis:latest
    container_name: redash_redis
    restart: always